### ISSUE TITLE
Could not host the app.

### ISSUE THREAD

**Issue by TheAnshul756** [piratos/dotter-app#2]
I followed your medium blog, and I am unable to host the app. It is showing 
 No such file or directory: '/home/piratos/courses/djangotraced/debug.log'

I think the error is because of the following line 145 in dotter-app/dotter/dotter/settings.py
'filename': '/home/anshul/courses/djangotraced/debug.log',
and I'm not sure what is to insert in place of this filename.

**Comment by sayf-eddine-scality** [comment]
Hello
Yep I missed changing that hardcoded path, you can change that path to any folder you want or make it always in the basedir of the project.

change `/home/piratos/courses/djangotraced/debug.log` into `"{0}/debug.log".format(BASE_DIR)`

**Comment by TheAnshul756** [comment]
Hello
Thanks for that. It resolved that error. But now it is giving another error:
TypeError: trace() got an unexpected keyword argument 'view'
which I think is because of line 77 in dotter-app/dotter/home/views.py
@tracing.trace(view=False)
in that annotation you are passing view=False argument which is unexpected as given in error.

**Comment by sayf-eddine-scality** [comment]
You are still using the default implementation.
I added support for across view tracing in my fork. Had that in the article
>So I forked the project and played around the code to enable tracing function calls inside the view by adding an option to the decorator to differentiate between a view and a other function calls

>you can fork or clone and install my version from my github account https://github.com/piratos/python-django
>After installing the forked version of django_opentracing, lunch the app and try to create a graph

**Comment by TheAnshul756** [comment]
ok got it. Thanks a lot.
