### ISSUE TITLE
FileNotFoundError at /graph

### ISSUE THREAD

**Issue by TheAnshul756** [piratos/dotter-app#5]
Hello
I setup your app as you mentioned in your blog, but I'm getting error while trying to create a graph.

> Environment:
> 
> 
> Request Method: POST
> Request URL: http://localhost:8000/graph
> 
> Django Version: 3.0.3
> Python Version: 3.7.6
> Installed Applications:
> ['django.contrib.admin',
>  'django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.staticfiles',
>  'home']
> Installed Middleware:
> ['django_opentracing.OpenTracingMiddleware',
>  'django.middleware.security.SecurityMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware']
> 
> 
> 
> Traceback (most recent call last):
>   File "/home/anshul.asawa/Desktop/work/dotter-app/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
>     response = get_response(request)
>   File "/home/anshul.asawa/Desktop/work/dotter-app/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/home/anshul.asawa/Desktop/work/dotter-app/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/home/anshul.asawa/Desktop/work/dotter-app/dotter/home/views.py", line 68, in graphing
>     request, name, content, user, parent_view='graphing'
>   File "/home/anshul.asawa/Desktop/work/dotter-app/lib/python3.7/site-packages/django_opentracing/tracing.py", line 65, in wrapper
>     r = view_func(request, *args, **kwargs)
>   File "/home/anshul.asawa/Desktop/work/dotter-app/dotter/home/views.py", line 90, in create_graph
>     check_call(['dot', '-Tpng', dotfile_name, '-o', pngfile_name])
>   File "/usr/lib64/python3.7/subprocess.py", line 358, in check_call
>     retcode = call(*popenargs, **kwargs)
>   File "/usr/lib64/python3.7/subprocess.py", line 339, in call
>     with Popen(*popenargs, **kwargs) as p:
>   File "/usr/lib64/python3.7/subprocess.py", line 800, in __init__
>     restore_signals, start_new_session)
>   File "/usr/lib64/python3.7/subprocess.py", line 1551, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> 
> Exception Type: FileNotFoundError at /graph
> Exception Value: [Errno 2] No such file or directory: 'dot': 'dot'
> 

Please have a look.

**Comment by sayf-eddine-scality** [comment]
the application uses the binary `dot` to render the graphs. you need to install `graphviz` on your system

**Comment by TheAnshul756** [comment]
thanks a lot. that worked.
